"""Equity ingestion and analysis materialization contracts."""

from .domain import (
    BarAvailabilityMode,
    BarSessionScope,
    BarSourceKind,
    ContextStatus,
    DecisionWatermark,
    EquityBarRevision,
    EquityContextSnapshot,
    EquityEvidence,
    EvidenceRole,
    EvidenceType,
    FundamentalReport,
    LifecycleStatus,
    QualityState,
    SecurityReferenceRevision,
)
from .repositories import (
    EquityAnalysisRepository,
    EquityBarRepository,
    EquityEvidenceRepository,
    EquityIngestionRepository,
    EquityOutcomeRepository,
    EquityReferenceRepository,
    EquityUniverseRepository,
)
from .polygon import (
    PolygonEquityClient,
    conservative_filing_availability,
    normalize_fundamental_reports,
    normalize_native_bars,
    normalize_security_reference,
)
from .materialization import (
    MaterializationResult,
    derive_session_hourly_frame,
    materialize_equity_evidence,
)
from .derivation import derive_canonical_bars
from .context import build_equity_context
from .orchestration import (
    BarPublicationResult,
    EquityMaterializationService,
    FundamentalRefreshResult,
    OutcomeRunResult,
    QualificationRunResult,
    ReconciliationRunResult,
)
from .outcomes import (
    OutcomePolicy,
    ResearchOutcome,
    default_directional_policy,
    evaluate_directional_outcome,
    recommendation_plan_policy,
)
from .qualification import (
    QualificationRevision,
    qualify_option_conditioning,
    qualify_outcomes,
)
from .polygon_stream import PolygonAdvancedStreamClient
from .stream import (
    EquityStreamProcessor,
    SessionBarAccumulator,
    StreamBatchResult,
    normalize_stream_minute,
    reconcile_interval_bar,
)
from .technicals import (
    EmaConfirmation,
    TradeSetupTechnicals,
    assess_momentum,
    compute_ema_confirmation,
    compute_trade_setup_technicals,
    detect_golden_cross,
    detect_level_retests,
    detect_setup_candlesticks,
    exponential_moving_average,
)
from .setup_composition import (
    DirectionComposition,
    TradeLevelComposition,
    compose_fibonacci_context,
    compose_setup_confluence,
    compose_setup_direction,
    compose_setup_duration,
    compose_setup_timing,
    compose_trade_levels,
)

__all__ = [
    "BarAvailabilityMode",
    "BarSessionScope",
    "BarPublicationResult",
    "BarSourceKind",
    "ContextStatus",
    "DecisionWatermark",
    "DirectionComposition",
    "EquityAnalysisRepository",
    "EquityBarRepository",
    "EquityBarRevision",
    "EquityContextSnapshot",
    "EquityEvidence",
    "EquityEvidenceRepository",
    "EquityIngestionRepository",
    "EquityMaterializationService",
    "FundamentalRefreshResult",
    "EquityOutcomeRepository",
    "EquityReferenceRepository",
    "EquityStreamProcessor",
    "EquityUniverseRepository",
    "EmaConfirmation",
    "EvidenceRole",
    "EvidenceType",
    "FundamentalReport",
    "LifecycleStatus",
    "MaterializationResult",
    "OutcomePolicy",
    "OutcomeRunResult",
    "QualityState",
    "QualificationRevision",
    "QualificationRunResult",
    "ReconciliationRunResult",
    "ResearchOutcome",
    "PolygonEquityClient",
    "PolygonAdvancedStreamClient",
    "SessionBarAccumulator",
    "SecurityReferenceRevision",
    "StreamBatchResult",
    "TradeSetupTechnicals",
    "TradeLevelComposition",
    "compose_fibonacci_context",
    "assess_momentum",
    "conservative_filing_availability",
    "compute_ema_confirmation",
    "compute_trade_setup_technicals",
    "compose_setup_direction",
    "compose_setup_confluence",
    "compose_setup_duration",
    "compose_setup_timing",
    "compose_trade_levels",
    "build_equity_context",
    "normalize_fundamental_reports",
    "normalize_native_bars",
    "normalize_security_reference",
    "normalize_stream_minute",
    "reconcile_interval_bar",
    "materialize_equity_evidence",
    "default_directional_policy",
    "detect_level_retests",
    "detect_golden_cross",
    "detect_setup_candlesticks",
    "derive_session_hourly_frame",
    "derive_canonical_bars",
    "evaluate_directional_outcome",
    "exponential_moving_average",
    "qualify_option_conditioning",
    "qualify_outcomes",
    "recommendation_plan_policy",
]